[tool.poetry]
name = "harmonyrestorer"
version = "0.1.0"
description = "Audio Restoration App"
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = ">=3.9,<3.10"
flask = "2.0.1"
werkzeug = "2.0.1"
numpy = "1.21.6"
scipy = "1.7.3"
librosa = "0.8.1"
soundfile = "0.10.3.post1"
gunicorn = "20.1.0"
flask-caching = "1.10.1"
pydub = "0.25.1"
pyrubberband = "0.3.0"
torch = {version = "2.0.1+cpu", source = "torch_cpu"}
torchaudio = {version = "2.0.1+cpu", source = "torch_cpu"}

[tool.poetry.dev-dependencies]

[[tool.poetry.source]]
name = "torch_cpu"
url = "https://download.pytorch.org/whl/cpu"
priority = "explicit"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
