[tool.poetry]
name = "harmonyrestorer"
version = "0.1.0"
description = "Audio Restoration App"
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.8"
flask = "2.0.1"
numpy = "1.22.0"
torch = "2.1.0"
librosa = "0.8.1"
soundfile = "0.10.3.post1"
gunicorn = "20.1.0"
flask-caching = "1.10.1"
werkzeug = "2.0.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
